"use client";

import { CheckCircle2, FileSpreadsheet, UploadCloud, UsersRound } from "lucide-react";
import { useId, useState } from "react";

export type UploadCardProps = { kind: "peserta" | "nilai"; title: string; description: string; disabled?: boolean; onFileChange?: (file: File | null) => void };

export function UploadCard({ kind, title, description, disabled = false, onFileChange }: UploadCardProps) {
  const inputId = useId(); const [fileName, setFileName] = useState(""); const isPeserta = kind === "peserta"; const Icon = isPeserta ? UsersRound : FileSpreadsheet; const hasFile = Boolean(fileName);
  const accent = isPeserta ? "bg-blue-100 text-blue-700 hover:border-blue-400 hover:bg-blue-50" : "bg-emerald-100 text-emerald-700 hover:border-emerald-500 hover:bg-emerald-50";
  const button = isPeserta ? "bg-blue-700 hover:bg-blue-800" : "bg-emerald-600 hover:bg-emerald-700";
  return <article className="flex min-h-[292px] flex-col rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition-shadow hover:shadow-md"><div className="flex items-center gap-4"><div className={`grid size-12 place-items-center rounded-full ${accent.split(" ").slice(0, 2).join(" ")}`}><Icon size={23} /></div><div><h2 className="text-base font-semibold text-slate-900">{title}</h2><p className="mt-1 text-xs leading-5 text-slate-500">{description}</p></div></div><label className={`mt-5 flex flex-1 flex-col items-center justify-center rounded-xl border-2 border-dashed p-5 text-center transition ${disabled ? "cursor-not-allowed border-slate-200 bg-slate-50 opacity-60" : hasFile ? "cursor-pointer border-emerald-300 bg-emerald-50 text-emerald-700" : `cursor-pointer border-slate-200 bg-slate-50 ${accent}`}`} htmlFor={inputId}>{hasFile ? <CheckCircle2 size={38} strokeWidth={1.7} /> : <UploadCloud size={38} strokeWidth={1.6} />}<p className="mt-3 text-sm font-semibold text-slate-700">{hasFile ? "File siap diproses" : "Upload file Excel di sini"}</p><span className="mt-1 text-xs text-slate-500">{hasFile ? "Klik untuk mengganti file" : "Format .xlsx atau .xls"}</span><span className={`mt-3 rounded-lg px-4 py-2 text-xs font-bold text-white shadow-sm transition ${button}`}>{hasFile ? "Ganti File" : "Pilih File"}</span><input accept=".xlsx,.xls" className="sr-only" disabled={disabled} id={inputId} onChange={(event) => { const file = event.target.files?.[0] ?? null; setFileName(file?.name ?? ""); onFileChange?.(file); }} type="file" /></label><p className={`mt-3 truncate text-center text-xs font-medium ${hasFile ? "text-emerald-700" : "text-slate-500"}`}>{fileName || "Maksimum ukuran file 50MB"}</p></article>;
}
